name: Deploy Frontend a VPS

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
    runs-on: [self-hosted, production]

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Verificar entorno en la VPS
        run: |
          echo "Servidor de Oracle - FRONTEND"
          docker --version
          docker compose version
          
      - name: Actualizar repositorio de infraestructura
        run: |
          cd /opt/novatech-solutions/runner/_work/infrastructure/infrastructure
          git pull origin main

      - name: Reconstruir y desplegar imagen Docker del Frontend
        run: |
          cd /opt/novatech-solutions/runner/_work/infrastructure/infrastructure
          docker compose up -d --build frontend
